// Mock data for shops and products
import 'package:myapp/shared/model/product_detail.dart';
import 'package:myapp/shared/model/shop.dart';
import 'package:myapp/shared/model/product.dart';

final services = [
  {
    'icon': "assets/images/Home1.png",
    'label': 'Dịch vụ chăm sóc thú cưng',
    'key': 'care',
  },
  {
    'icon': "assets/images/Home2.png",
    'label': 'Sức khỏe và vệ sinh',
    'key': 'health',
  },
  {
    'icon': "assets/images/Home3.png",
    'label': 'Thức ăn và dinh dưỡng',
    'key': 'food',
  },
  {
    'icon': "assets/images/Home4.png",
    'label': 'Phụ kiện và đồ dùng',
    'key': 'accessory',
  },
  {'icon': "assets/images/Home5.png", 'label': 'Y tế thú y', 'key': 'medical'},
  {'icon': "assets/images/Home6.png", 'label': 'Khác', 'key': 'other'},
];

final mockShops = [
  Shop(
    shopId: 'shop_001',
    owner: 'owner_001@example.com',
    shopName: 'Pet Food Store',
    description: 'Premium pet food and accessories',
    status: true,
    workingDays: 'Mon-Sat',
  ),
  Shop(
    shopId: 'shop_002',
    owner: 'owner_002@example.com',
    shopName: 'Pet Grooming Center',
    description: 'Professional grooming services',
    status: true,
    workingDays: 'Tue-Sun',
  ),
  Shop(
    shopId: 'shop_003',
    owner: 'owner_003@example.com',
    shopName: 'Pet Health Clinic',
    description: 'Veterinary services and pet healthcare',
    status: true,
    workingDays: 'Mon-Sun',
  ),
  Shop(
    shopId: 'shop_004',
    owner: 'owner_004@example.com',
    shopName: 'Pet Accessories Shop',
    description: 'Quality pet accessories and toys',
    status: true,
    workingDays: 'Mon-Sat',
  ),
];

final mockProducts = [
  // CARE - Dịch vụ chăm sóc thú cưng (10 items)
  Product(
    productId: 'care_001',
    shopId: 'shop_002',
    productName: 'Full Grooming Package',
    description: 'Bath, haircut and nail trimming',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_001",
      productId: 'care_001',
      price: 150000,
      discount: true,
      isDefault: true,
      quantityInStock: 50,
    ),
  ),
  Product(
    productId: 'care_002',
    shopId: 'shop_002',
    productName: 'Basic Bath Service',
    description: 'Professional bathing with premium shampoo',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_002",
      productId: 'care_002',
      price: 80000,
      discount: false,
      isDefault: true,
      quantityInStock: 100,
    ),
  ),
  Product(
    productId: 'care_003',
    shopId: 'shop_002',
    productName: 'Nail Trimming Service',
    description: 'Safe and professional nail care',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_003",
      productId: 'care_003',
      price: 40000,
      discount: false,
      isDefault: true,
      quantityInStock: 80,
    ),
  ),
  Product(
    productId: 'care_004',
    shopId: 'shop_002',
    productName: 'Ear Cleaning Service',
    description: 'Gentle ear cleaning and health check',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_004",
      productId: 'care_004',
      price: 35000,
      discount: true,
      isDefault: true,
      quantityInStock: 60,
    ),
  ),
  Product(
    productId: 'care_005',
    shopId: 'shop_002',
    productName: 'De-shedding Treatment',
    description: 'Reduce shedding with special brushing technique',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_005",
      productId: 'care_005',
      price: 70000,
      discount: false,
      isDefault: true,
      quantityInStock: 40,
    ),
  ),
  Product(
    productId: 'care_006',
    shopId: 'shop_002',
    productName: 'Dental Cleaning Service',
    description: 'Professional pet dental care',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_006",
      productId: 'care_006',
      price: 120000,
      discount: true,
      isDefault: true,
      quantityInStock: 30,
    ),
  ),
  Product(
    productId: 'care_007',
    shopId: 'shop_002',
    productName: 'Flea Treatment Service',
    description: 'Complete flea removal and prevention',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_007",
      productId: 'care_007',
      price: 90000,
      discount: false,
      isDefault: true,
      quantityInStock: 45,
    ),
  ),
  Product(
    productId: 'care_008',
    shopId: 'shop_002',
    productName: 'Premium Spa Package',
    description: 'Luxury spa treatment for pampered pets',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_008",
      productId: 'care_008',
      price: 250000,
      discount: true,
      isDefault: true,
      quantityInStock: 20,
    ),
  ),
  Product(
    productId: 'care_009',
    shopId: 'shop_002',
    productName: 'Mobile Grooming Service',
    description: 'Grooming service at your home',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_009",
      productId: 'care_009',
      price: 200000,
      discount: false,
      isDefault: true,
      quantityInStock: 25,
    ),
  ),
  Product(
    productId: 'care_010',
    shopId: 'shop_002',
    productName: 'Express Grooming',
    description: 'Quick 30-minute grooming service',
    status: true,
    category: 'care',
    productDetail: ProductDetail(
      id: "care_010",
      productId: 'care_010',
      price: 100000,
      discount: true,
      isDefault: true,
      quantityInStock: 70,
    ),
  ),

  // HEALTH - Sức khỏe và vệ sinh (10 items)
  Product(
    productId: 'health_001',
    shopId: 'shop_001',
    productName: 'Pet Shampoo',
    description: 'Gentle shampoo for sensitive skin',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_001",
      productId: 'health_001',
      price: 45000,
      discount: false,
      isDefault: true,
      quantityInStock: 80,
    ),
  ),
  Product(
    productId: 'health_002',
    shopId: 'shop_001',
    productName: 'Anti-Flea Shampoo',
    description: 'Special formula to prevent fleas and ticks',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_002",
      productId: 'health_002',
      price: 65000,
      discount: true,
      isDefault: true,
      quantityInStock: 60,
    ),
  ),
  Product(
    productId: 'health_003',
    shopId: 'shop_001',
    productName: 'Pet Toothpaste',
    description: 'Safe enzymatic toothpaste for pets',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_003",
      productId: 'health_003',
      price: 35000,
      discount: false,
      isDefault: true,
      quantityInStock: 120,
    ),
  ),
  Product(
    productId: 'health_004',
    shopId: 'shop_001',
    productName: 'Ear Cleaner Solution',
    description: 'Gentle ear cleaning formula',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_004",
      productId: 'health_004',
      price: 40000,
      discount: true,
      isDefault: true,
      quantityInStock: 90,
    ),
  ),
  Product(
    productId: 'health_005',
    shopId: 'shop_001',
    productName: 'Pet Wipes',
    description: 'Antibacterial cleaning wipes',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_005",
      productId: 'health_005',
      price: 25000,
      discount: false,
      isDefault: true,
      quantityInStock: 150,
    ),
  ),
  Product(
    productId: 'health_006',
    shopId: 'shop_001',
    productName: 'Deodorizing Spray',
    description: 'Natural deodorizer for pets',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_006",
      productId: 'health_006',
      price: 50000,
      discount: true,
      isDefault: true,
      quantityInStock: 70,
    ),
  ),
  Product(
    productId: 'health_007',
    shopId: 'shop_001',
    productName: 'Paw Balm',
    description: 'Healing balm for dry and cracked paws',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_007",
      productId: 'health_007',
      price: 30000,
      discount: false,
      isDefault: true,
      quantityInStock: 85,
    ),
  ),
  Product(
    productId: 'health_008',
    shopId: 'shop_001',
    productName: 'Dry Shampoo',
    description: 'Waterless cleaning for busy pet owners',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_008",
      productId: 'health_008',
      price: 55000,
      discount: true,
      isDefault: true,
      quantityInStock: 65,
    ),
  ),
  Product(
    productId: 'health_009',
    shopId: 'shop_001',
    productName: 'Wound Care Spray',
    description: 'Antiseptic spray for minor cuts',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_009",
      productId: 'health_009',
      price: 75000,
      discount: false,
      isDefault: true,
      quantityInStock: 40,
    ),
  ),
  Product(
    productId: 'health_010',
    shopId: 'shop_001',
    productName: 'Pet Vitamins Spray',
    description: 'Daily vitamin supplement in spray form',
    status: true,
    category: 'health',
    productDetail: ProductDetail(
      id: "health_010",
      productId: 'health_010',
      price: 80000,
      discount: true,
      isDefault: true,
      quantityInStock: 55,
    ),
  ),

  // FOOD - Thức ăn và dinh dưỡng (10 items)
  Product(
    productId: 'food_001',
    shopId: 'shop_001',
    productName: 'Premium Dog Food',
    description: 'High-quality nutrition for adult dogs',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_001",
      productId: 'food_001',
      price: 50000,
      discount: true,
      isDefault: true,
      quantityInStock: 100,
    ),
  ),
  Product(
    productId: 'food_002',
    shopId: 'shop_001',
    productName: 'Puppy Food',
    description: 'Specially formulated for growing puppies',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_002",
      productId: 'food_002',
      price: 55000,
      discount: false,
      isDefault: true,
      quantityInStock: 80,
    ),
  ),
  Product(
    productId: 'food_003',
    shopId: 'shop_001',
    productName: 'Cat Food - Indoor',
    description: 'Complete nutrition for indoor cats',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_003",
      productId: 'food_003',
      price: 45000,
      discount: true,
      isDefault: true,
      quantityInStock: 90,
    ),
  ),
  Product(
    productId: 'food_004',
    shopId: 'shop_001',
    productName: 'Senior Pet Food',
    description: 'Easy-to-digest formula for older pets',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_004",
      productId: 'food_004',
      price: 60000,
      discount: false,
      isDefault: true,
      quantityInStock: 70,
    ),
  ),
  Product(
    productId: 'food_005',
    shopId: 'shop_001',
    productName: 'Grain-Free Dog Food',
    description: 'Natural grain-free formula',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_005",
      productId: 'food_005',
      price: 75000,
      discount: true,
      isDefault: true,
      quantityInStock: 65,
    ),
  ),
  Product(
    productId: 'food_006',
    shopId: 'shop_001',
    productName: 'Wet Cat Food',
    description: 'Delicious pate in various flavors',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_006",
      productId: 'food_006',
      price: 15000,
      discount: false,
      isDefault: true,
      quantityInStock: 200,
    ),
  ),
  Product(
    productId: 'food_007',
    shopId: 'shop_001',
    productName: 'Dog Treats',
    description: 'Healthy training treats for dogs',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_007",
      productId: 'food_007',
      price: 25000,
      discount: true,
      isDefault: true,
      quantityInStock: 150,
    ),
  ),
  Product(
    productId: 'food_008',
    shopId: 'shop_001',
    productName: 'Cat Treats',
    description: 'Irresistible treats for cats',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_008",
      productId: 'food_008',
      price: 20000,
      discount: false,
      isDefault: true,
      quantityInStock: 180,
    ),
  ),
  Product(
    productId: 'food_009',
    shopId: 'shop_001',
    productName: 'Dental Chews',
    description: 'Chews that help clean teeth',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_009",
      productId: 'food_009',
      price: 35000,
      discount: true,
      isDefault: true,
      quantityInStock: 120,
    ),
  ),
  Product(
    productId: 'food_010',
    shopId: 'shop_001',
    productName: 'Freeze-Dried Treats',
    description: 'Premium freeze-dried meat treats',
    status: true,
    category: 'food',
    productDetail: ProductDetail(
      id: "food_010",
      productId: 'food_010',
      price: 85000,
      discount: false,
      isDefault: true,
      quantityInStock: 45,
    ),
  ),

  // ACCESSORY - Phụ kiện và đồ dùng (10 items)
  Product(
    productId: 'accessory_001',
    shopId: 'shop_004',
    productName: 'Cat Litter',
    description: 'Natural clumping litter',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_001",
      productId: 'accessory_001',
      price: 30000,
      discount: false,
      isDefault: true,
      quantityInStock: 200,
    ),
  ),
  Product(
    productId: 'accessory_002',
    shopId: 'shop_004',
    productName: 'Pet Bed - Medium',
    description: 'Comfortable cushioned bed for medium pets',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_002",
      productId: 'accessory_002',
      price: 120000,
      discount: true,
      isDefault: true,
      quantityInStock: 50,
    ),
  ),
  Product(
    productId: 'accessory_003',
    shopId: 'shop_004',
    productName: 'Dog Leash',
    description: 'Strong and durable nylon leash',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_003",
      productId: 'accessory_003',
      price: 40000,
      discount: false,
      isDefault: true,
      quantityInStock: 80,
    ),
  ),
  Product(
    productId: 'accessory_004',
    shopId: 'shop_004',
    productName: 'Food Bowl Set',
    description: 'Stainless steel food and water bowls',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_004",
      productId: 'accessory_004',
      price: 55000,
      discount: true,
      isDefault: true,
      quantityInStock: 75,
    ),
  ),
  Product(
    productId: 'accessory_005',
    shopId: 'shop_004',
    productName: 'Pet Carrier',
    description: 'Portable carrier for travel',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_005",
      productId: 'accessory_005',
      price: 150000,
      discount: false,
      isDefault: true,
      quantityInStock: 30,
    ),
  ),
  Product(
    productId: 'accessory_006',
    shopId: 'shop_004',
    productName: 'Scratching Post',
    description: 'Tall scratching post for cats',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_006",
      productId: 'accessory_006',
      price: 90000,
      discount: true,
      isDefault: true,
      quantityInStock: 40,
    ),
  ),
  Product(
    productId: 'accessory_007',
    shopId: 'shop_004',
    productName: 'Pet Collar',
    description: 'Adjustable collar with ID tag',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_007",
      productId: 'accessory_007',
      price: 25000,
      discount: false,
      isDefault: true,
      quantityInStock: 100,
    ),
  ),
  Product(
    productId: 'accessory_008',
    shopId: 'shop_004',
    productName: 'Interactive Toy',
    description: 'Puzzle toy to keep pets entertained',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_008",
      productId: 'accessory_008',
      price: 65000,
      discount: true,
      isDefault: true,
      quantityInStock: 60,
    ),
  ),
  Product(
    productId: 'accessory_009',
    shopId: 'shop_004',
    productName: 'Pet Blanket',
    description: 'Soft fleece blanket for comfort',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_009",
      productId: 'accessory_009',
      price: 45000,
      discount: false,
      isDefault: true,
      quantityInStock: 85,
    ),
  ),
  Product(
    productId: 'accessory_010',
    shopId: 'shop_004',
    productName: 'Litter Box',
    description: 'Large covered litter box with filter',
    status: true,
    category: 'accessory',
    productDetail: ProductDetail(
      id: "accessory_010",
      productId: 'accessory_010',
      price: 180000,
      discount: true,
      isDefault: true,
      quantityInStock: 25,
    ),
  ),

  // MEDICAL - Y tế thú y (10 items)
  Product(
    productId: 'medical_001',
    shopId: 'shop_003',
    productName: 'Vet Consultation',
    description: 'Professional veterinary consultation',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_001",
      productId: 'medical_001',
      price: 120000,
      discount: true,
      isDefault: true,
      quantityInStock: 30,
    ),
  ),
  Product(
    productId: 'medical_002',
    shopId: 'shop_003',
    productName: 'Vaccination Package',
    description: 'Complete vaccination program',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_002",
      productId: 'medical_002',
      price: 350000,
      discount: false,
      isDefault: true,
      quantityInStock: 50,
    ),
  ),
  Product(
    productId: 'medical_003',
    shopId: 'shop_003',
    productName: 'Health Checkup',
    description: 'Comprehensive health examination',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_003",
      productId: 'medical_003',
      price: 200000,
      discount: true,
      isDefault: true,
      quantityInStock: 40,
    ),
  ),
  Product(
    productId: 'medical_004',
    shopId: 'shop_003',
    productName: 'Deworming Treatment',
    description: 'Internal parasite treatment',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_004",
      productId: 'medical_004',
      price: 80000,
      discount: false,
      isDefault: true,
      quantityInStock: 70,
    ),
  ),
  Product(
    productId: 'medical_005',
    shopId: 'shop_003',
    productName: 'Dental Cleaning',
    description: 'Professional dental cleaning under anesthesia',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_005",
      productId: 'medical_005',
      price: 500000,
      discount: true,
      isDefault: true,
      quantityInStock: 20,
    ),
  ),
  Product(
    productId: 'medical_006',
    shopId: 'shop_003',
    productName: 'Spay/Neuter Surgery',
    description: 'Safe sterilization surgery',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_006",
      productId: 'medical_006',
      price: 800000,
      discount: false,
      isDefault: true,
      quantityInStock: 15,
    ),
  ),
  Product(
    productId: 'medical_007',
    shopId: 'shop_003',
    productName: 'Emergency Care',
    description: '24/7 emergency veterinary care',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_007",
      productId: 'medical_007',
      price: 300000,
      discount: true,
      isDefault: true,
      quantityInStock: 25,
    ),
  ),
  Product(
    productId: 'medical_008',
    shopId: 'shop_003',
    productName: 'Blood Test Package',
    description: 'Complete blood work analysis',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_008",
      productId: 'medical_008',
      price: 250000,
      discount: false,
      isDefault: true,
      quantityInStock: 35,
    ),
  ),
  Product(
    productId: 'medical_009',
    shopId: 'shop_003',
    productName: 'X-Ray Examination',
    description: 'Digital X-ray imaging service',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_009",
      productId: 'medical_009',
      price: 180000,
      discount: true,
      isDefault: true,
      quantityInStock: 45,
    ),
  ),
  Product(
    productId: 'medical_010',
    shopId: 'shop_003',
    productName: 'Prescription Medication',
    description: 'Veterinary prescribed medications',
    status: true,
    category: 'medical',
    productDetail: ProductDetail(
      id: "medical_010",
      productId: 'medical_010',
      price: 100000,
      discount: false,
      isDefault: true,
      quantityInStock: 60,
    ),
  ),

  // OTHER - Khác (10 items)
  Product(
    productId: 'other_001',
    shopId: 'shop_004',
    productName: 'Pet Toy',
    description: 'Fun interactive toy for pets',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_001",
      productId: 'other_001',
      price: 25000,
      discount: false,
      isDefault: true,
      quantityInStock: 150,
    ),
  ),
  Product(
    productId: 'other_002',
    shopId: 'shop_004',
    productName: 'Pet Training Course',
    description: 'Basic obedience training program',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_002",
      productId: 'other_002',
      price: 400000,
      discount: true,
      isDefault: true,
      quantityInStock: 20,
    ),
  ),
  Product(
    productId: 'other_003',
    shopId: 'shop_004',
    productName: 'Pet Insurance',
    description: 'Monthly pet health insurance plan',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_003",
      productId: 'other_003',
      price: 150000,
      discount: false,
      isDefault: true,
      quantityInStock: 100,
    ),
  ),
  Product(
    productId: 'other_004',
    shopId: 'shop_004',
    productName: 'Pet Photography Session',
    description: 'Professional pet photo shoot',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_004",
      productId: 'other_004',
      price: 200000,
      discount: true,
      isDefault: true,
      quantityInStock: 15,
    ),
  ),
  Product(
    productId: 'other_005',
    shopId: 'shop_004',
    productName: 'Pet Birthday Party Package',
    description: 'Celebration package for pet birthdays',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_005",
      productId: 'other_005',
      price: 300000,
      discount: false,
      isDefault: true,
      quantityInStock: 10,
    ),
  ),
  Product(
    productId: 'other_006',
    shopId: 'shop_004',
    productName: 'Pet Microchip Service',
    description: 'Microchip implantation for identification',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_006",
      productId: 'other_006',
      price: 100000,
      discount: true,
      isDefault: true,
      quantityInStock: 50,
    ),
  ),
  Product(
    productId: 'other_007',
    shopId: 'shop_004',
    productName: 'Pet Taxi Service',
    description: 'Transportation service for pets',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_007",
      productId: 'other_007',
      price: 80000,
      discount: false,
      isDefault: true,
      quantityInStock: 30,
    ),
  ),
  Product(
    productId: 'other_008',
    shopId: 'shop_004',
    productName: 'Pet Hotel Booking',
    description: 'Overnight boarding service',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_008",
      productId: 'other_008',
      price: 120000,
      discount: true,
      isDefault: true,
      quantityInStock: 25,
    ),
  ),
  Product(
    productId: 'other_009',
    shopId: 'shop_004',
    productName: 'Pet Memorial Service',
    description: 'Respectful pet memorial arrangements',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_009",
      productId: 'other_009',
      price: 250000,
      discount: false,
      isDefault: true,
      quantityInStock: 5,
    ),
  ),
  Product(
    productId: 'other_010',
    shopId: 'shop_004',
    productName: 'Pet DNA Testing',
    description: 'Genetic testing to identify breed and health risks',
    status: true,
    category: 'other',
    productDetail: ProductDetail(
      id: "other_010",
      productId: 'other_010',
      price: 350000,
      discount: true,
      isDefault: true,
      quantityInStock: 40,
    ),
  ),
];
